
/*
-- Query: SELECT * FROM antsquests.corsi
*/
INSERT INTO antsquests.corsi (id_corso,nome,data_inizio,data_fine) VALUES (1,'Java','2022-06-19','2024-06-19');
INSERT INTO antsquests.corsi (id_corso,nome,data_inizio,data_fine) VALUES (2,'Gol Aprile2024','2022-06-19','2023-06-19');
INSERT INTO antsquests.corsi (id_corso,nome,data_inizio,data_fine) VALUES (3,'Java Base','2020-06-19','2022-06-19');
INSERT INTO antsquests.corsi (id_corso,nome,data_inizio,data_fine) VALUES (4,'Java Intermedio','2020-07-23','2022-07-18');
INSERT INTO antsquests.corsi (id_corso,nome,data_inizio,data_fine) VALUES (5,'Java Avanzato','2021-05-18','2024-06-23');
INSERT INTO antsquests.corsi (id_corso,nome,data_inizio,data_fine) VALUES (6,'java',NULL,'2024-07-16');

/*
-- Query: SELECT * FROM antsquests.quests
*/
INSERT INTO antsquests.quests (id_qst,categoria_id,titolo) VALUES (1,'I','Logica');
INSERT INTO antsquests.quests (id_qst,categoria_id,titolo) VALUES (2,'I','Java Base');
INSERT INTO antsquests.quests (id_qst,categoria_id,titolo) VALUES (3,'I','Java Intermedio');

/*
-- Query: SELECT * FROM antsquests.quests_details
*/
INSERT INTO antsquests.quests_details (id_qst_det,quest_id,domanda) VALUES (1,1,'se mario ha due mele ne mangia 3 quante mele ha ?');
INSERT INTO antsquests.quests_details (id_qst_det,quest_id,domanda) VALUES (2,1,'se il sole scotta, devo mettermi la crema ?');

/*
-- Query: SELECT * FROM antsquests.answers_qsts
*/
INSERT INTO antsquests.answers_qsts (id_ans,quest_detail_id,risposta,corretta) VALUES (1,1,'tutte',1);
INSERT INTO antsquests.answers_qsts (id_ans,quest_detail_id,risposta,corretta) VALUES (2,1,'nessuna',0);
INSERT INTO antsquests.answers_qsts (id_ans,quest_detail_id,risposta,corretta) VALUES (3,2,'vero',1);
INSERT INTO antsquests.answers_qsts (id_ans,quest_detail_id,risposta,corretta) VALUES (4,2,'falso',0);


/*
-- Query: SELECT * FROM antsquests.users + antsquests.studenti
*/
-- passkey: 123
insert into antsquests.users(username_email, passkey, ruolo) values('mrossi@gmail.com', '$2a$12$Q4ZMWHjFZZ7nyy3CAY8cQu2ikiXVGoaYPXoBY.QQcwRe1fqacFHcW', 'studente');
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values((select max(id_usr) from antsquests.users), 'MARIO', 'ROSSI', '1990-01-01', '20100', 'MI', '3211231212', '1');
insert into antsquests.users(username_email, passkey, ruolo) values('lverdi@gmail.com', '$2a$12$Q4ZMWHjFZZ7nyy3CAY8cQu2ikiXVGoaYPXoBY.QQcwRe1fqacFHcW', 'guest');
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono) values((select max(id_usr) from antsquests.users), 'LUIGI', 'VERDI', '1990-01-01', '20100', 'MI', '3211231212');

insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('kstops0@google.ru', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('anoorwood1@microsoft.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('fpaolicchi2@joomla.org', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('bdymott3@bloglovin.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('esiveter4@accuweather.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('lvarnam5@boston.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('fmaypother6@ocn.ne.jp', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('kmulqueen7@tiny.cc', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('badam8@msn.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('lphilbin9@opera.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('lhansela@auda.org.au', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('cflugerb@digg.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('hhowlingsc@merriam-webster.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('kshapirad@engadget.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('iweste@slideshare.net', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('ddessantf@usa.gov', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('lbrockleyg@dropbox.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('htaltonh@usgs.gov', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('raldingtoni@comcast.net', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('ksaenzj@exblog.jp', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('rmcdunlevyk@1und1.de', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mjahnell@fema.gov', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('slissimorem@mapy.cz', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('bpaolicchin@state.gov', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('wbarreauo@cbsnews.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mronaghanp@nbcnews.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('dgaffeyq@goodreads.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('emannockr@ebay.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('eiannettis@economist.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('vvipant@spotify.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('bbenediteu@tuttocitta.it', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mvellacottv@mac.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('cquarringtonw@webeden.co.uk', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('qglavesx@themeforest.net', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('bdeboldy@phpbb.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('nbainbridgez@free.fr', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('arevance10@ca.gov', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('aruffli11@elpais.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('rmoodie12@de.vu', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('ltall13@tumblr.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mdeniseau14@ted.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('dwilcher15@wordpress.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('kcantor16@netvibes.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('pjahncke17@altervista.org', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('cmcrory18@ifeng.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('lstockwell19@xing.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('ggalpen1a@plala.or.jp', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mgarces1b@msu.edu', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('kmillyard1c@globo.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mriguard1d@hibu.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('hnapoli1e@nydailynews.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('blangshaw1f@netscape.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('egeany1g@wired.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('jlutz1h@rakuten.co.jp', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('teickhoff1i@redcross.org', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('fmaccaig1j@shop-pro.jp', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('auc1k@ted.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('fcowle1l@hibu.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('tmcenery1m@foxnews.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('wmanby1n@arstechnica.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mfriedank1o@weebly.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mwebley1p@slashdot.org', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('ckmicicki1q@unesco.org', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('hemerson1r@ft.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('aallsopp1s@sciencedirect.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('dabbay1t@mac.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('aausiello1u@un.org', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('fcottrill1v@apache.org', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('emoorhead1w@storify.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('tbehrend1x@seattletimes.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('llalley1y@webnode.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('selby1z@usda.gov', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mspriggin20@bloglovin.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('otraice21@loc.gov', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('atuma22@ycombinator.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('alearoyd23@discuz.net', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('echolomin24@prnewswire.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mruppert25@facebook.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('ppentecost26@goodreads.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('kgiraldon27@oakley.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('jblain28@arstechnica.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('vraddin29@ehow.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('cmather2a@who.int', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('nleap2b@economist.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('rwitchard2c@mit.edu', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('ekorda2d@smh.com.au', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('rdemanche2e@shutterfly.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('mhekkert2f@tmall.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('lbrigden2g@ycombinator.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('paucock2h@nydailynews.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('ehawson2i@europa.eu', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('kkibbel2j@sakura.ne.jp', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('greina2k@soundcloud.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('gdadge2l@cnn.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('bverduin2m@acquirethisname.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', true);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('abows2n@nba.com', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'studente', false);
insert into antsquests.users (username_email, passkey, ruolo, first_time) values ('kallenby2o@upenn.edu', '$2a$12$L7D/DvZcH/y/WrS35YtHKONSChnv.61whg8juicDHdhqjIiWGDdmS', 'guest', true);

insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (4, 'Rriocard', 'Snoding', '2003-02-19', '26340', null, '633-625-6573', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (5, 'Rowland', 'Zanetello', '2002-08-29', '62385', null, '287-981-3353', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (6, 'Moss', 'Southcombe', '2004-04-06', null, null, '559-364-0471', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (7, 'Robin', 'Evenett', '1999-06-26', '5831', null, '826-399-5158', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (8, 'Guthrie', 'Robjohns', '1993-01-07', null, null, '786-852-2317', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (9, 'Trish', 'Hulse', '1993-10-15', '5972', null, '140-138-4592', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (10, 'Bunny', 'Frowen', '2001-10-19', null, null, '311-762-2233', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (11, 'Blisse', 'Swigger', '1995-11-15', null, null, '926-777-7254', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (12, 'Norrie', 'Fern', '1997-08-07', null, null, '557-905-8820', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (13, 'Lil', 'Matteacci', '1993-06-14', null, null, '125-666-4855', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (14, 'Niven', 'Jamme', '1997-11-15', null, null, '881-965-8749', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (15, 'Roxine', 'Blackett', '1999-01-12', '33410', null, '890-100-6470', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (16, 'Prue', 'Perulli', '2001-06-21', null, null, '397-690-6114', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (17, 'Brooke', 'Held', '2004-05-19', null, null, '393-368-0535', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (18, 'Retha', 'Jeffree', '1999-12-20', '22510', '14', '511-638-4075', 1);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (19, 'Cherida', 'Gudde', '2001-06-02', null, null, '121-873-3730', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (20, 'Whitney', 'Fernandez', '1992-03-21', '34430', null, '674-383-4517', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (21, 'Melicent', 'Showl', '2000-01-17', '3580', null, '933-886-7046', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (22, 'Chrystel', 'Milroy', '2002-07-26', null, null, '298-806-1153', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (23, 'Therine', 'Abrahmovici', '1999-08-20', null, null, '904-617-3942', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (24, 'Charmion', 'Jenkison', '2001-10-27', null, null, '335-634-4882', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (25, 'Timoteo', 'Layburn', '1997-10-27', null, null, '765-574-4705', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (26, 'Noel', 'Keemer', '1993-05-31', '19730', null, '197-942-8062', 1);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (27, 'Mariel', 'Maven', '1995-05-30', null, null, '662-656-1788', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (28, 'Shelley', 'Penquet', '2003-08-19', '9601', null, '600-439-2558', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (29, 'Sula', 'Brown', '2002-03-14', '39210', null, '524-333-8451', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (30, 'Alessandro', 'Lodin', '1997-01-06', null, null, '816-833-2125', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (31, 'Pebrook', 'McReidy', '1997-04-25', '40687', 'GR', '724-402-5242', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (32, 'Drucill', 'Cordel', '2004-01-07', null, null, '710-341-8079', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (33, 'Roth', 'Comusso', '1992-03-27', null, null, '894-135-5176', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (34, 'Ruy', 'Tatlock', '1999-05-16', '36046', null, '998-498-2140', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (35, 'Rosie', 'Oseman', '2002-06-01', null, null, '302-846-7932', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (36, 'Stephie', 'Durno', '2000-07-26', null, null, '689-973-3586', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (37, 'Justus', 'O''Riordan', '1990-01-12', '34130', null, '112-344-6017', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (38, 'Isaak', 'Sandilands', '1990-09-18', '54018', null, '354-411-3590', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (39, 'Marcy', 'Watkinson', '1997-07-26', '35553', '18', '577-647-5243', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (40, 'Gauthier', 'Pena', '1999-07-20', null, null, '714-621-2907', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (41, 'Ilyssa', 'Persent', '1996-02-17', null, null, '492-694-0857', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (42, 'Adolf', 'Gidney', '1993-07-15', null, null, '338-704-2497', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (43, 'Ozzie', 'Kliemke', '1992-02-29', '1119', null, '157-882-4787', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (44, 'Clerkclaude', 'Hunnisett', '2001-01-13', null, null, '241-814-7408', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (45, 'Mikkel', 'Farge', '1998-03-10', null, null, '288-856-1813', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (46, 'Lyell', 'Rushmare', '2004-02-18', '30323', 'GA', '770-909-4211', 1);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (47, 'Merline', 'Tarver', '1997-03-26', '76130', null, '908-298-9614', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (48, 'Dulce', 'Gilding', '1999-06-11', '34105', null, '920-950-5668', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (49, 'Fonz', 'Danelut', '1993-10-28', '97323', 'BD', '489-951-5692', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (50, 'Gloriane', 'Benoit', '1995-08-13', null, null, '913-240-7293', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (51, 'Lazare', 'Gwyn', '1995-09-10', null, null, '201-946-1333', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (52, 'Aurea', 'McQuaid', '1998-08-22', null, null, '545-308-7319', 1);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (53, 'Sigmund', 'Jerok', '1998-10-26', null, null, '599-226-1988', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (54, 'Sorcha', 'Volcker', '2001-04-16', null, null, '846-305-1874', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (55, 'Marven', 'Allon', '1995-07-10', null, null, '179-574-6487', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (56, 'Patsy', 'Tregoning', '1993-09-15', null, null, '766-242-6802', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (57, 'Kermy', 'Pitherick', '1990-04-06', null, null, '294-940-5019', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (58, 'Livvie', 'O''Docherty', '1999-07-13', null, null, '886-541-3429', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (59, 'Kris', 'Dorn', '1990-09-20', null, null, '893-508-4774', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (60, 'Armand', 'Mitrovic', '2000-05-28', null, null, '599-759-3623', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (61, 'Cathrin', 'Wilmott', '1994-09-09', '9303', null, '339-116-9052', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (62, 'Jedidiah', 'McCafferty', '2000-11-08', null, null, '416-652-0889', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (63, 'Dode', 'McGrath', '1990-08-05', '36190', null, '530-211-3351', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (64, 'Jethro', 'Rioch', '1995-06-18', null, null, '766-680-9348', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (65, 'Marie-jeanne', 'Cecil', '2003-04-24', null, null, '892-924-3345', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (66, 'Christi', 'Mably', '1999-02-12', null, null, '657-713-7657', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (67, 'Tammy', 'Dipple', '1998-01-08', '90055', 'CA', '213-963-9192', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (68, 'Devin', 'Montgomery', '1997-08-29', null, null, '612-371-8318', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (69, 'Jayson', 'Isaak', '1994-11-24', '3610', null, '562-709-0996', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (70, 'Tait', 'Bonallack', '1994-11-02', null, null, '534-655-5277', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (71, 'Noach', 'Brazier', '1992-03-26', '77708', 'A8', '579-372-6205', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (72, 'Dewain', 'Rennebach', '1993-05-08', '41821', 'GR', '231-941-4268', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (73, 'Caryn', 'Bonelle', '1993-05-13', null, null, '475-387-0332', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (74, 'Doti', 'Lafontaine', '1994-02-28', '20355', null, '855-587-7050', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (75, 'Mace', 'Ivanusyev', '1994-08-23', '45457', '01', '857-309-2193', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (76, 'Jessalin', 'Ginty', '1994-07-26', '6431', null, '574-148-7992', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (77, 'Bertrando', 'Dunlop', '1998-08-08', null, null, '237-509-4095', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (78, 'Laurena', 'Batisse', '1993-03-26', '45356', '01', '403-566-3430', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (79, 'Kiley', 'Learmonth', '1992-04-25', '18274', 'AB', '656-528-0173', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (80, 'Catlee', 'Cunningham', '1990-04-03', null, null, '261-905-8724', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (81, 'Lemmy', 'Endle', '1990-08-20', null, null, '548-809-1266', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (82, 'Hunter', 'Trewett', '1990-07-20', null, null, '614-590-5832', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (83, 'Mariquilla', 'Pidwell', '2000-12-14', null, null, '554-136-3930', 1);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (84, 'Pietro', 'Rasher', '1998-06-08', null, null, '259-677-4540', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (85, 'Fernando', 'Eland', '1995-03-10', '67607', null, '552-716-3206', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (86, 'Tommy', 'Foat', '2004-01-06', '26000', null, '570-311-5717', 2);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (87, 'Florinda', 'Gammidge', '2001-08-20', 'G5N', 'QC', '891-738-1783', 4);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (88, 'Carlen', 'Budd', '1992-08-20', '9610', null, '212-785-7775', 1);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (89, 'Frants', 'Fleeming', '1994-12-01', null, null, '335-254-6745', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (90, 'Briant', 'Jeffrey', '1995-05-11', '57000', null, '213-739-9896', 1);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (91, 'Ciel', 'Knowlton', '2003-08-22', '81405', null, '640-775-9636', 3);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (92, 'Amanda', 'Von Helmholtz', '2002-11-24', null, null, '976-560-6700', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (93, 'Cristin', 'Lorenzetto', '1996-06-01', null, null, '331-150-1831', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (94, 'Flore', 'Elbourn', '1999-07-07', null, null, '490-356-5631', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (95, 'Rodrigo', 'Shoard', '1995-02-03', null, null, '828-117-4826', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (96, 'Emmott', 'Greeveson', '1991-06-01', null, null, '604-944-5246', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (97, 'Herold', 'Cannam', '1992-09-12', '6711', null, '118-448-0319', 6);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (98, 'Antonie', 'Dye', '1996-01-18', '20344', null, '116-662-1466', 5);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (99, 'Wilburt', 'Camocke', '1994-02-13', '3187', null, '885-594-9217', null);
insert into antsquests.studenti(user_id, nome, cognome, data_nascita, cap, provincia, telefono, corso_id) values (100, 'Tersina', 'Kesteven', '2002-08-18', null, null, '503-715-1902', 1);


/*
-- Query: SELECT * FROM antsquests.esiti_quests
*/
INSERT INTO antsquests.esiti_quests (id_est_qst,quest_id,data_esecuzione,punteggio,tempo,studente_id) VALUES (1,1,'2024-05-01','12','10',1);
INSERT INTO antsquests.esiti_quests (id_est_qst,quest_id,data_esecuzione,punteggio,tempo,studente_id) VALUES (2,1,'2024-06-01','9','10',1);
INSERT INTO antsquests.esiti_quests (id_est_qst,quest_id,data_esecuzione,punteggio,tempo,studente_id) VALUES (3,2,'2024-07-01','20','10',2);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 94, '1/10', '1995-01-06', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 58, '5/10', '1999-01-16', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 94, '1/10', '2003-02-15', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 61, '10/10', '2003-12-20', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 62, '3/10', '1998-04-18', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 22, '1/10', '2001-09-07', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 57, '4/10', '1996-06-10', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 33, '6/10', '2003-08-09', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 40, '6/10', '1993-05-19', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 49, '2/10', '2002-10-16', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 7, '4/10', '1992-05-06', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 69, '5/10', '1993-04-20', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 99, '3/10', '1998-04-05', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 40, '6/10', '1992-09-26', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 29, '3/10', '2002-08-07', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 68, '8/10', '2002-12-24', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 12, '10/10', '2004-03-26', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 81, '9/10', '2001-07-25', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 94, '5/10', '1990-04-06', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 2, '1/10', '1997-09-24', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 83, '6/10', '1997-05-26', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 53, '10/10', '1999-05-07', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 92, '5/10', '2003-05-14', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 82, '1/10', '2002-07-06', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 53, '10/10', '1995-08-18', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 11, '6/10', '2000-01-17', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 32, '10/10', '1992-09-20', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 9, '7/10', '2001-08-20', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 19, '3/10', '1997-05-03', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 28, '3/10', '1998-06-09', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 54, '10/10', '2000-11-24', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 41, '6/10', '1991-08-07', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 33, '4/10', '1999-01-06', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 50, '3/10', '2001-10-11', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 72, '1/10', '2002-08-09', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 29, '2/10', '1992-10-27', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 51, '2/10', '1994-05-03', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 85, '6/10', '1990-11-25', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 16, '3/10', '2004-06-22', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 81, '4/10', '1999-01-23', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 86, '9/10', '2000-09-05', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 9, '10/10', '1992-12-24', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 50, '9/10', '2000-06-17', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 1, '6/10', '2000-09-08', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 52, '7/10', '2001-04-20', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 30, '9/10', '2000-07-04', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 17, '6/10', '1993-12-21', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 22, '6/10', '1995-07-24', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 62, '8/10', '2002-04-19', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 12, '9/10', '2004-02-05', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 25, '8/10', '2000-03-24', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 7, '5/10', '1995-12-17', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 87, '7/10', '1996-03-26', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 8, '8/10', '2000-12-24', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 78, '3/10', '1993-06-19', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 23, '6/10', '1994-08-08', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 51, '2/10', '2001-03-04', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 96, '8/10', '1994-05-04', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 3, '6/10', '1990-06-21', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 34, '2/10', '1998-06-28', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 22, '1/10', '1996-10-15', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 64, '8/10', '2002-04-16', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 73, '5/10', '1991-10-28', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 13, '3/10', '1992-05-31', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 48, '8/10', '2003-10-17', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 85, '4/10', '1993-07-30', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 16, '4/10', '2002-06-25', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 59, '5/10', '2000-03-28', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 11, '8/10', '2000-10-05', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 40, '1/10', '1991-03-12', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 42, '8/10', '1990-11-26', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 3, '8/10', '1993-12-01', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 6, '5/10', '1999-07-09', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 79, '9/10', '1993-08-15', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 99, '7/10', '2000-08-21', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 77, '8/10', '1999-11-02', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 14, '7/10', '1997-05-21', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 54, '8/10', '2003-05-12', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 66, '3/10', '1992-02-05', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 10, '2/10', '1995-09-09', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 4, '5/10', '2002-07-18', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 63, '7/10', '1997-07-21', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 1, '6/10', '1998-09-10', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 25, '9/10', '1999-12-08', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 11, '6/10', '1993-08-19', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 85, '1/10', '2001-07-21', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 82, '3/10', '1999-04-26', 10);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 70, '1/10', '1999-07-19', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 61, '2/10', '1999-01-28', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 82, '10/10', '1992-11-28', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 86, '9/10', '1994-10-26', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 51, '4/10', '1990-12-06', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 4, '8/10', '1992-12-07', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 8, '8/10', '2004-04-23', 60);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 77, '4/10', '2001-11-27', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 53, '3/10', '1991-04-14', 50);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (3, 54, '8/10', '1990-05-06', 40);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 23, '4/10', '1992-09-21', 30);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (1, 84, '9/10', '1994-09-04', 20);
insert into antsquests.esiti_quests (quest_id, studente_id, punteggio, data_esecuzione, tempo) values (2, 81, '7/10', '1999-08-05', 50);
